import 'package:flutter/material.dart';
import 'app_theme_manager.dart';
import 'background_image_config.dart';

/// v3.0 P0：主题注册中心
///
/// 负责内置主题的 const 定义、用户主题的运行时 CRUD、
/// 启动时将所有主题注册到 [AppThemeManager]。
///
/// 重构说明（v1.4.5 → v3.0）：
/// - 6 个内置主题从原 `AppThemeManager._themes` 内嵌 const Map 迁移至此独立文件
/// - 原 `selectedBlue` 字段已重命名为 `selectedAccent`（BUG-01 修复时同步进行）
/// - 新增 `seedColor` 字段（BUG-01 修复）：每个主题的 ColorScheme 种子色
/// - 新增 BUG-06 修复字段：`placeholderCover`、`titleBrown`、`starGold`、
///   `infoBlue`、`brandBlue`、`infoBg`
/// - 原 `backgroundImagePath` + `backgroundOverlayOpacity` 收敛为
///   `BackgroundImageConfig`（v3.0 P0 重构）
class ThemeRegistry {
  ThemeRegistry._();

  static bool _initialized = false;

  /// 启动时调用：注册所有内置主题到 AppThemeManager
  /// 调用位置：main.dart main() 初始化阶段（在 loadSavedTheme 之前）
  static void registerBuiltinThemes() {
    if (_initialized) return;
    final manager = AppThemeManager.instance;
    for (final data in _builtinThemes) {
      manager.registerTheme(data);
    }
    _initialized = true;
  }

  /// 重置（仅测试用）
  static void resetForTest() {
    _initialized = false;
  }

  /// 6 个内置主题的完整定义
  static const List<CTThemeData> _builtinThemes = [
    // ============ 暖阳（warmSun）============
    CTThemeData(
      id: 'warmSun',
      source: CTThemeSource.builtin,
      name: '暖阳',
      emoji: '🌞',
      description: '经典暖棕复古风格',
      isFeatured: false,
      backgroundImage: BackgroundImageConfig.none(),
      brightness: Brightness.light,
      seedColor: Color(0xFF8B7355),
      background: Color(0xFFFDFBF7),
      sidebarBackground: Color(0xFFFBF6EF),
      titleBarBackground: Color(0xFFFBF6EF),
      primaryText: Color(0xFF5C4A3D),
      secondaryText: Color(0xFFA08264),
      border: Color(0xFF8B7355),
      borderLight: Color(0x338B7355),
      buttonBackground: Color(0xFFF0E6D2),
      selectedAccent: Color(0xFFB4D4FF),
      dangerRed: Color(0xFFD4183D),
      placeholderText: Color(0xFFC4B3A1),
      placeholderBg: Color(0xFFF5F1E8),
      addCoverBg: Color(0xFFE9E0D1),
      shadowColor: Color(0x408B7355),
      successGreen: Color(0xFF4CAF50),
      successBg: Color(0xFFE8F5E9),
      errorBg: Color(0xFFFFE6EA),
      hoverCloseBg: Color(0xFFFFEBEE),
      hoverCloseBorder: Color(0xFFEF5350),
      inputHint: Color(0x99A08264),
      cardHoverBg: Color(0xFFF5EDE6),
      navActiveBg: Color(0xFFFFFFFF),
      navActiveBorder: Color(0xFFA07840),
      navInactiveBorder: Color(0xFFC8B49A),
      toggleBg: Color(0xFFE8E0D0),
      toggleBorder: Color(0xFFC8B49A),
      toggleIcon: Color(0xFF5C3A1A),
      placeholderCover: Color(0xFFE9E0D1),
      titleBrown: Color(0xFF5C4A3D),
      starGold: Color(0xFFD4A017),
      infoBlue: Color(0xFF4A72A5),
      brandBlue: Color(0xFF6B9EAD),
      infoBg: Color(0xFFE6F0FF),
      // v4.0 探索详情页令牌：暖阳 = 设计稿原值（1:1 复刻基准主题）
      accentCyan: Color(0xFF2DA6D4),
      accentInk: Color(0xFF262626),
      accentViolet: Color(0xFF6841C4),
      dividerStrong: Color(0xFF2B2B2B),
      heartRed: Color(0xFFDD1B24),
      feedbackGreen: Color(0xFF00AD38),
    ),
    // ============ 浅色（frost）—— 系统级现代浅色主题 ============
    // 设计语言「极光 Aurora」· 中性色系 =「石英白」方案（用户指定，2026-09-12）：
    // 侧导航 #F8F9FA / 卡片纯白 / 主文字 #1C1B1F / 辅助 #49454F / 分割线 #CAC4D0，
    // 强调色保持科技蓝 #3E6FE8，观感为石英白 + 柔光。
    // 完整令牌表见 docs/DEV/features/modern_theme_aurora_redesign.md §4（含修订记录）。
    CTThemeData(
      id: 'frost',
      source: CTThemeSource.builtin,
      name: '浅色',
      emoji: '❄️',
      description: '现代石英白 · 柔光科技感',
      isFeatured: false,
      backgroundImage: BackgroundImageConfig.none(),
      brightness: Brightness.light,
      visualStyle: CTVisualStyle.aurora,
      warningAmber: Color(0xFFB97D10),
      seedColor: Color(0xFF3E6FE8),
      background: Color(0xFFF8F9FA),
      sidebarBackground: Color(0xFFF8F9FA),
      titleBarBackground: Color(0xFFF8F9FA),
      primaryText: Color(0xFF1C1B1F),
      secondaryText: Color(0xFF49454F),
      border: Color(0xFFCAC4D0),
      borderLight: Color(0x59CAC4D0),
      buttonBackground: Color(0xFFFFFFFF),
      selectedAccent: Color(0xFF3E6FE8),
      dangerRed: Color(0xFFE5484D),
      placeholderText: Color(0xFF79747E),
      placeholderBg: Color(0xFFEFF0F3),
      addCoverBg: Color(0xFFE9EAEE),
      shadowColor: Color(0x241C1B1F),
      successGreen: Color(0xFF2FA46C),
      successBg: Color(0xFFE4F5EC),
      errorBg: Color(0xFFFDEBEE),
      hoverCloseBg: Color(0xFFFDEBEE),
      hoverCloseBorder: Color(0xFFE5484D),
      inputHint: Color(0x9949454F),
      cardHoverBg: Color(0xFFECEEF1),
      navActiveBg: Color(0xFFFFFFFF),
      navActiveBorder: Color(0xFF3E6FE8),
      navInactiveBorder: Color(0xFFCAC4D0),
      toggleBg: Color(0xFFE9EAEE),
      toggleBorder: Color(0xFFCAC4D0),
      toggleIcon: Color(0xFF49454F),
      placeholderCover: Color(0xFFE9EAEE),
      titleBrown: Color(0xFF1C1B1F),
      starGold: Color(0xFFF2A93B),
      infoBlue: Color(0xFF4377D6),
      brandBlue: Color(0xFF5B8DEF),
      infoBg: Color(0xFFEAF1FE),
      // v4.0 探索详情页令牌：石英白底 → 青蓝压深一档保证白底对比
      accentCyan: Color(0xFF1189BC),
      accentInk: Color(0xFF262626),
      accentViolet: Color(0xFF6841C4),
      dividerStrong: Color(0xFF1C1B1F),
      heartRed: Color(0xFFE5484D),
      feedbackGreen: Color(0xFF2FA46C),
    ),
    // ============ 深色（obsidian）—— 系统级现代深色主题 ============
    // 深空蓝黑底 + 提亮一级面板 + 亮科技蓝强调；与浅色（frost）成对。
    // 完整令牌表见 docs/DEV/features/modern_theme_aurora_redesign.md §4。
    CTThemeData(
      id: 'obsidian',
      source: CTThemeSource.builtin,
      name: '深色',
      emoji: '🌑',
      description: '现代深空蓝黑 · 轻科技感',
      isFeatured: false,
      backgroundImage: BackgroundImageConfig.none(),
      brightness: Brightness.dark,
      visualStyle: CTVisualStyle.aurora,
      warningAmber: Color(0xFFF5C04A),
      seedColor: Color(0xFF4E8DF5),
      background: Color(0xFF0F141F),
      sidebarBackground: Color(0xFF131926),
      titleBarBackground: Color(0xFF131926),
      primaryText: Color(0xFFE7ECF5),
      secondaryText: Color(0xFF8D99AE),
      border: Color(0xFF2F3B52),
      borderLight: Color(0x332F3B52),
      buttonBackground: Color(0xFF1A2233),
      selectedAccent: Color(0xFF5B8DEF),
      dangerRed: Color(0xFFF0666E),
      placeholderText: Color(0xFF5C6880),
      placeholderBg: Color(0xFF1A2233),
      addCoverBg: Color(0xFF212B40),
      shadowColor: Color(0x66000000),
      successGreen: Color(0xFF4CC38A),
      successBg: Color(0xFF16281F),
      errorBg: Color(0xFF301A1F),
      hoverCloseBg: Color(0xFF301A1F),
      hoverCloseBorder: Color(0xFFF0666E),
      inputHint: Color(0x998D99AE),
      cardHoverBg: Color(0xFF232E45),
      navActiveBg: Color(0xFFFFFFFF),
      navActiveBorder: Color(0xFF35549E),
      navInactiveBorder: Color(0xFF2F3B52),
      toggleBg: Color(0xFF1A2233),
      toggleBorder: Color(0xFF2F3B52),
      toggleIcon: Color(0xFFB6C2D9),
      placeholderCover: Color(0xFF212B40),
      titleBrown: Color(0xFFE7ECF5),
      starGold: Color(0xFFF5C04A),
      infoBlue: Color(0xFF6FA5F2),
      brandBlue: Color(0xFF5B8DEF),
      infoBg: Color(0xFF1A2742),
      // v4.0 探索详情页令牌：深空底 → 青蓝/紫提亮，ink 反转为近白
      accentCyan: Color(0xFF4FB3E8),
      accentInk: Color(0xFFE7ECF5),
      accentViolet: Color(0xFF9B7BE8),
      dividerStrong: Color(0xFFE7ECF5),
      heartRed: Color(0xFFFF5A63),
      feedbackGreen: Color(0xFF4CC38A),
    ),
    // ============ 墨绿金（mint）- 特色主题 ============
    CTThemeData(
      id: 'mint',
      source: CTThemeSource.builtin,
      name: '墨绿金',
      emoji: '🌊',
      description: '神秘墨绿流金，奢华魔幻',
      isFeatured: true,
      backgroundImage: BackgroundImageConfig.bundled(
        'assets/images/themes/dark_emerald_gold.png',
        overlayOpacity: 0.20,
      ),
      brightness: Brightness.dark,
      seedColor: Color(0xFF4A9B6A),
      background: Color(0xFF1A3D35),
      sidebarBackground: Color(0xFF15302A),
      titleBarBackground: Color(0xFF15302A),
      primaryText: Color(0xFFF0F4EC),
      secondaryText: Color(0xFFB8D4C0),
      border: Color(0xFF4A9B6A),
      borderLight: Color(0x334A9B6A),
      buttonBackground: Color(0x99D4AF37),
      selectedAccent: Color(0xFFE8C84A),
      dangerRed: Color(0xFFE86A6A),
      placeholderText: Color(0xFF7A9B88),
      placeholderBg: Color(0x25D4AF37),
      addCoverBg: Color(0x30D4AF37),
      shadowColor: Color(0x70D4AF37),
      successGreen: Color(0xFF8DDD8D),
      successBg: Color(0x252A5A3E),
      errorBg: Color(0x255A2A2A),
      hoverCloseBg: Color(0x255A2A2A),
      hoverCloseBorder: Color(0xFFE86A6A),
      inputHint: Color(0x99B8D4C0),
      cardHoverBg: Color(0x18FFFFFF),
      navActiveBg: Color(0xD01A3D35),
      navActiveBorder: Color(0xFFE8C84A),
      navInactiveBorder: Color(0x604A9B6A),
      toggleBg: Color(0x99D4AF37),
      toggleBorder: Color(0xFF4A9B6A),
      toggleIcon: Color(0xFFE8C84A),
      placeholderCover: Color(0x30D4AF37),
      titleBrown: Color(0xFFE8C84A),
      starGold: Color(0xFFE8C84A),
      infoBlue: Color(0xFF6B9EAD),
      brandBlue: Color(0xFF4A9B6A),
      infoBg: Color(0x254A9B6A),
      // v4.0 探索详情页令牌：墨绿金 → 分割线取主题流金色
      accentCyan: Color(0xFF4FB3E8),
      accentInk: Color(0xFFF0F4EC),
      accentViolet: Color(0xFF9B7BE8),
      dividerStrong: Color(0xFFE8C84A),
      heartRed: Color(0xFFFF6B6B),
      feedbackGreen: Color(0xFF8DDD8D),
    ),
    // ============ 樱花浪漫（sakura）- 特色主题 ============
    CTThemeData(
      id: 'sakura',
      source: CTThemeSource.builtin,
      name: '樱花浪漫',
      emoji: '🌸',
      description: '粉色樱花飘落，梦幻唯美',
      isFeatured: true,
      // 取景整体下移露出人物头部（2026-09-13 用户指定）：
      // 1387x1080 竖比例图在典型画布下 cover 纵向溢出 ~16%，top 对齐 =
      // 画面下移约 10% 窗高，头部完整入画且不至过度
      backgroundImage: BackgroundImageConfig.bundled(
        'assets/images/themes/sakura.png',
        overlayOpacity: 0.25,
        alignment: BackgroundImageAlignment.top,
      ),
      brightness: Brightness.light,
      seedColor: Color(0xFFD4849A),
      background: Color(0xFFFDF2F6),
      sidebarBackground: Color(0xFFF9ECF1),
      titleBarBackground: Color(0xFFF9ECF1),
      primaryText: Color(0xFF5C2E3E),
      secondaryText: Color(0xFFB07A90),
      border: Color(0xFFD4849A),
      borderLight: Color(0x33D4849A),
      buttonBackground: Color(0xCCFFB7C5),
      selectedAccent: Color(0xFFE88BA0),
      dangerRed: Color(0xFFC44060),
      placeholderText: Color(0xFFCC99AA),
      placeholderBg: Color(0x1AFFB7C5),
      addCoverBg: Color(0x25FFB7C5),
      shadowColor: Color(0x40D4849A),
      successGreen: Color(0xFF4CAF50),
      successBg: Color(0x20E8F5E9),
      errorBg: Color(0x20FFE6EA),
      hoverCloseBg: Color(0x20FFE6EA),
      hoverCloseBorder: Color(0xFFEF5350),
      inputHint: Color(0x99B07A90),
      cardHoverBg: Color(0x10FFB7C5),
      navActiveBg: Color(0xE0FDF2F6),
      navActiveBorder: Color(0xFFE88BA0),
      navInactiveBorder: Color(0x80D4849A),
      toggleBg: Color(0xCCFFB7C5),
      toggleBorder: Color(0xFFD4849A),
      toggleIcon: Color(0xFFC44060),
      placeholderCover: Color(0x25FFB7C5),
      titleBrown: Color(0xFF5C2E3E),
      starGold: Color(0xFFD4A017),
      infoBlue: Color(0xFF4A72A5),
      brandBlue: Color(0xFFE88BA0),
      infoBg: Color(0x20FFB7C5),
      // v4.0 探索详情页令牌：樱花 → ink/分割线取主题深梅色
      accentCyan: Color(0xFF2DA6D4),
      accentInk: Color(0xFF5C2E3E),
      accentViolet: Color(0xFF6841C4),
      dividerStrong: Color(0xFF5C2E3E),
      heartRed: Color(0xFFDD1B24),
      feedbackGreen: Color(0xFF4CAF50),
    ),
    // ============ 蓝天白云（ocean）- 特色主题 ============
    CTThemeData(
      id: 'ocean',
      source: CTThemeSource.builtin,
      name: '蓝天白云',
      emoji: '☁️',
      description: '清新蓝天白云，自由开阔',
      isFeatured: true,
      backgroundImage: BackgroundImageConfig.bundled(
        'assets/images/themes/blue_sky.png',
        overlayOpacity: 0.20,
      ),
      brightness: Brightness.light,
      seedColor: Color(0xFF4A90D9),
      background: Color(0xFFE8F4FC),
      sidebarBackground: Color(0xFFDEEBF7),
      titleBarBackground: Color(0xFFDEEBF7),
      primaryText: Color(0xFF2A4A6A),
      secondaryText: Color(0xFF6A8FA8),
      border: Color(0xFF7BAACC),
      borderLight: Color(0x337BAACC),
      buttonBackground: Color(0xBFE8F4FC),
      selectedAccent: Color(0xFF4A90D9),
      dangerRed: Color(0xFFD44040),
      placeholderText: Color(0xFF8BB8CC),
      placeholderBg: Color(0x1587CEEB),
      addCoverBg: Color(0x2087CEEB),
      shadowColor: Color(0x407BAACC),
      successGreen: Color(0xFF3A9D5A),
      successBg: Color(0x20E8F5E9),
      errorBg: Color(0x20FFE6EA),
      hoverCloseBg: Color(0x20FFE6EA),
      hoverCloseBorder: Color(0xFFEF5350),
      inputHint: Color(0x996A8FA8),
      cardHoverBg: Color(0x1087CEEB),
      navActiveBg: Color(0xDDE8F4FC),
      navActiveBorder: Color(0xFF4A90D9),
      navInactiveBorder: Color(0x607BAACC),
      toggleBg: Color(0xBFE8F4FC),
      toggleBorder: Color(0xFF7BAACC),
      toggleIcon: Color(0xFF2A5A8A),
      placeholderCover: Color(0x2087CEEB),
      titleBrown: Color(0xFF2A4A6A),
      starGold: Color(0xFFD4A017),
      infoBlue: Color(0xFF4A90D9),
      brandBlue: Color(0xFF6B9EAD),
      infoBg: Color(0xFFE6F0FC),
      // v4.0 探索详情页令牌：蓝天 → ink/分割线取主题深蓝
      accentCyan: Color(0xFF2DA6D4),
      accentInk: Color(0xFF2A4A6A),
      accentViolet: Color(0xFF6841C4),
      dividerStrong: Color(0xFF2A4A6A),
      heartRed: Color(0xFFDD1B24),
      feedbackGreen: Color(0xFF3A9D5A),
    ),
  ];
}
